Added a description for the general code structure
skunkforce/OmniView pull request #95
Opened 2024-02-05 14:13 UTC by AKMaily

Added a description of the general code structure in the ReadMe. This structure is intended to be incorporated into the code in the coming weeks, leading to improved readability.

2024-02-05 14:19 UTC, bjoekeldude requested changes

2024-02-05 14:19 UTC, bjoekeldude commented on README.md
> +Namespaces should only be used when needed.
What does that even mean?

2024-02-05 14:24 UTC, AKMaily commented on README.md
> +Namespaces should only be used when needed.
It means we want to implement namespaces for the PlotRegions to pretend potential conflicts that may arise when functions are declared multiple times in an open-source project. However, we dont want to overload the project with unnecessary namespaces.

2024-02-08 16:59 UTC, R-Abbasi reviewed
https://github.com/skunkforce/OmniView/issues/92#issuecomment-1934548429

2024-04-19 09:01 UTC, bjoekeldude approved these changes

2024-04-19 09:33 UTC, R-Abbasi commented on README.md
> +Every function that does not depend on another function should be implemented in an individual .cpp file.
That is likely wrong, I guess. 
Assigning a source file to each function ends up having many TUs making managing the project harder on the one hand and increasing compilation time (since supposedly an object file needs to be created for each TU) on the other hand.

2024-04-19 11:28 UTC, merged